### ISSUE TITLE
How to set the StorageRoot for Media manager from the xml files ?

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#10]

**Comment by raghu-bhandi** [comment]
use mediaStorageFolderPath="someFolderPathThatIsAvailableToBothWebAndAppLayer" for example
mediaStorageFolderPath="e:/storage/attachments/" or
mediaStorageFolderPath="/usr/storage/"

**Comment by archetana** [comment]
In which file should we set this? Application.com or service

**Comment by raghu-bhandi** [comment]
application.xml. This is considered to be an "infrastructure", and hence is common for all services. 
This is for the default plug-in. we can design more sophisticated plugin for project on a need basis.
