### ISSUE TITLE
Setting mediaStorageFolderPath and mediStorageAssistantClass in the application.xml, seems to set the default assistant to MediaFolder, how do we set the media assistant to be custom mediStorageAssistantClass ?

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#11]

**Comment by raghu-bhandi** [comment]
Use mediStorageAssistantClass="" attribute of application.xml. This is a fully qualified class that implements MediaStorageAssistant interface.

If you use mediaStorageFolderPath="" it is assumed that you are using the built-in plugin. Hence you can not use both these attributes.
