### ISSUE TITLE
Defined a custom concat function in the service, but it is not not called, the default implementation gets called

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#16]

**Comment by raghu-bhandi** [comment]
How did you define a custom function inside a service? There is no such facility. 
Functions are to be defined at the application level and specified in an .xml file inside comp/fn folder. This similar to dataType. name specified for a function has to be unique across all files. (We do not expect such large number of functions, and hence this design)

We have defined 'concat' as an example. There is no way to over-ride that. You can replace it if you want a different implementation for the same.

Components like dataType, message and function have to have unique name across all files, while records and service names are qualified with folder structure.
