### ISSUE TITLE
How do we use the usertoken

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#19]

**Comment by raghu-bhandi** [comment]
userToken is either the password, or it is the SSO token, depending on the set-up. userToekn and useId are available as fields in your serviceContext with predefined names _userId and _userToken. (ctx.getValue("_userToken") in your java class, or use simply fieldName="_userId" in your actions)

designated loginService MUST return userId as a sesison field. This is achieved by using sessionFieldNames="a,b,c..." in outputData tag in service.xml

we will publish examples for different scenarios of login/security for more clarity

**Comment by raghu-bhandi** [comment]
Simplity had its own security layer using 'user-token'. This is discotinued, and hence userToken concept is not used anymore.
