### ISSUE TITLE
Expressions in setvalue, can we assign function calls

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#2]

**Comment by raghu-bhandi** [comment]
yes. expressions can contain functions like foo(a, b, faa(12 + c, d - 14));
Functions are to be defined in the application. A class that implements Function interface can be used as a function. an AbstractFunction is provided that takes care of some boiler-plate code that is required to implement Function. It is easier to for you to extend AbstractFunction.
Function also need to be declared as component under comp/fn/ folder. This is similar to java classes being exposed as services using service/list/*.xml. Refer to tutorial.xml file under comp/fn/ folder
