### ISSUE TITLE
How to set up login with user id and password specific to my application?

### ISSUE THREAD

**Issue by raghu-bhandi** [simplity/simplity#24]
I have an application that requires authentication by user with userId and password. There is no SSO, or other such facility on our corporate network. How do I set up my application?

**Comment by raghu-bhandi** [comment]
**Step 1 - Server side set-up.**
In application.xml sessionHelperClassName="org.simplity.http.DefaultHelper".  

**Step 2 - create a login service **
Create your service.xml where you expect _userId and _userToken (we avoid using the  name password). That is you specify these two fields in <inputData><InputFields><InputField..../></inputData></inputFields>. Validate these as per your logic, typically you may do a readAction and use its esult to determine success-failure. Typycally, you also extract some user-specific fields, like roles, preferences etc.. that are to be pushed to session, so that they are available to all services. And, finally, use sessionFields="..." to list all session fields. _userId would be one of them. That indicates to the web-tier that the login is successful.

**step 3 - design a client page/panel to accept login credentials**
You should have a client-page where user can enter userId and password. This should be your home page, or better a pop-up. Use Simplity.login(userId, password, callBackFunctionOnSuccess, optionalCallBackFunctionOnFailure) on click of submit/login button. On success function should close the page/panel and take user to the home page.

**step4 - relogin on session-out**
It is possible that the user has not used the application for a while, and the server has sessioned-out for this connection. If client does not manage this aspect, and just sends a request, server responds back with a status indicating that there is no session. Such a response is also received if a request is sent before logging in. Typically, you would like to navigate to a login page, or pop-up such a panel and re-login. You can ask Simplity to call your function in such an event with Simplity.registerRelogin(fn).  This function is called back with serviceName, data, callBackOnSuccess and callBackOnFailure as parameters. These are the parameters with which the last getResponse was called. These parameters help you to provide a resend-request feature on successful relogin.

**Comment by raghu-bhandi** [comment]
Step1 : Design client side UI for login/relogin. Simplity.login(userId, password, callback....) is available to be called from your login page. Also, you may register your function to be called for relogin using Simplity.registerRelogin(fn). Whenever a service request returns with a not-logged-in status, simplity will call your fn.

Step 2 : design a login service. This service will get _userId and _userToken as fields in ctx. Do whatever you have to do and if the user is NOT authenticated, remove userId from ctx. (use setValue action with no fieldVaue). Of course you specify _userId as an outputfield, to send back the userId. Note that it is possible that he loginId could be different from userId. userId is typically used as foreign key in all tables, while loginId is used only for the user to login.

**Comment by archetana** [comment]
Closed
