### ISSUE TITLE
org.simplity.http.DefaultHelper not checked in 

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#27]

**Comment by raghu-bhandi** [comment]
SessionHelper design has been changed, and you do not need them any more. This is part of the simplification we got after dropping X-CSRF feature. 

If you you want to work with no login, for example during development, use utoLoginUserId="" in application.xml. This user id is automatically logged in. 

If this parameter is not set, a session with suserId is required. This is achieved by either a login from client (a._i is invoked) or HttpAgent.login() is called from the filter. If loginserviceName="" is set, that service is executed. This service should set userId as session field. If this service is not set, then a default (dummy) service is executed that simulates that the userId is authenticated. (Refer to ServiceAgent.login())

With the updated schema, you will notice that the sessionHelper attribute is not valid anymore.
