### ISSUE TITLE
Require a Batch service

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#38]

**Comment by raghu-bhandi** [comment]
A batch service is likely to run for long, and requires transaction management at a better granular level than one at the entire service level. 
1. long running : use executeInBackground="true" at the service level. Such a service will run on its own thread. Optionally, its result can still be pumped back to client if the service was triggered from a client.

2. transaction management : Use dbAccessType="subService". With this, the main service opens a read-only connection to the data base. Sub-service or complex-logic that require readWrite access create their own connections and manage transaction managements the way that suits them. All actions in the main service can continue to use the read-only connection.

These features should be enough for designing batch services

**Comment by archetana** [comment]
This is a duplicate of #49
