### ISSUE TITLE
InputField - defaultValue is not getting assigned

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#4]
Reference Unit test:
 ActionsTestNoDB.LogicTest
//Check for defaultValue assignment to Inputfield	

Config file:
Logic.xml

**Comment by raghu-bhandi** [comment]
Are you checking for the value of switch in the response? In that case, switch should be specified as an output field. You would have observed during your test run that the log indeed gives you the value of switch, but it is not found in response. include switch in your fieldNames="" attribute, and you should be fine.

**Comment by raghu-bhandi** [comment]
bug fixed. modified InputField.extractInput() method. tested with an example.
