### ISSUE TITLE
Required Additional Component

### ISSUE THREAD

**Issue by pakuni** [simplity/simplity#41]
-JMS Message Listeners for push/pull to/from MQ
- email
- Rolling log mechanism
- UI

**Comment by raghu-bhandi** [comment]
One of the requirements is that the message consumption and the service execution should be part of the same transaction. This can be achieved if we use an MDB that is managed by the container. It is possible for the onMessage() method of the MDB to invoke Simplity service using a simple method.

With this approach, we do not need any additional component. However, in a given project, if we observe any boiler-plate codes, we will come-up with a project-specific component that can eliminate such code.

Rolling-log mechanism is an aspect that is handled by the logger. Simplity works with the logger of your choice. (log4J, slf4J-simple, logback or jcl)

**Comment by archetana** [comment]
This is now available in the latest source
