### ISSUE TITLE
Datasheet capabilities:

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#47]
These are mainly methods that will be used in the Java classes for processing
1. Column-wise operations
    a. Column to array/set/list
       ex:Datasheet.toArray(Datasheet ds,int colIndex),Datasheet.toSet(Datasheet ds,int colIndex),Datasheet.toList(Datasheet ds,int colIndex)
    b. 2 Columns to Map
       ex: Datasheet.toMap(Datasheet ds,int colkeyIndex,int colvalueIndex)
2. Datasheet to array/set/list
     ex: Datasheet.toArray(Datasheet ds), Datasheet.toSet(Datasheet ds),Datasheet.toList(Datasheet ds)
3. Array/Set/List to Datasheet
    ex: Datasheet.toDatasheet(Array arr), Datasheet.toDatasheet(Set set),Datasheet.toDatasheet(List list)
4. Map to Datasheet
    a.  Datasheet.toDatasheet(Map map,boolean transpose). If transpose = true, the output datasheet will be a SingleRowDataSheet with keys as the column and values as the row. If transpose = false, the output datasheet will be MultiRowDatasheet with columns as "Key","Value" and corresponding rows.

**Comment by shaliniib** [comment]
Items to close for issue closure 
 
- [X]  Coding
- [X ] Unit tests
- [X ] Example
- [ ] Documentation
