### ISSUE TITLE
JMS Consumer

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#52]
The JMS Consumer action will receive messages from the Queue 
1. On demand
2. Listening continuously 

Items to close for issue closure
- [x] Coding
- [x] Unit tests
- [x] Example
- [x] Documentation

**Comment by archetana** [comment]
Bug: The jmsConsumer is getting the message on top of Queue

**Comment by rnmadhavan** [comment]
MessageType related tests will be implemented separately
