### ISSUE TITLE
Wiki restructuring

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#66]

**Comment by sMadhusmita** [comment]
Reference: https://github.com/lettuce-io/lettuce-core/wiki

Points to include in Wiki: 
 - [ ] 1. Home : 
                  - [ ] a. Simplity logo 
                  - [ ] b.Quick Navigation : Overview, Getting started, Downloads, Technical Documentation

 - [ ] 2. Custom sidebar : 
                  - [ ] 1. Intro : About simplity , Who uses ? 
                  - [ ] 2. Getting Started : Getting Started ( Get it, Start Coding) , Basic Usage , Transactions
                  - [ ] 3. Configurations
                  - [ ] 4. Services
                  - [ ] 5. On the fly services.
                  - [ ]  6. Security

 - [ ] 3. Pages:
                  - [ ] 1. Home
                  - [ ] 2. About Simplity
                  - [ ] 3. Getting Started (version wise)
                  - [ ] 4. Downloads ( version wise)
                  - [ ] 5. Technical Documentation ( all topics links)
