### ISSUE TITLE
BatchRowProcessor - File

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#72]

**Comment by archetana** [comment]
Includes support for input and output file

**Comment by sMadhusmita** [comment]
Items to close for issue closure
- [ ] Coding
- [ ] Unit tests
- [ ] Example
- [X] Documentation

**Comment by shaliniib** [comment]
Items to close for issue closure
- [X] Coding
- [X] Unit tests
- [X] Example
- [X] Documentation
