### ISSUE TITLE
Defaultvalue in record is not considered 

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#84]

**Comment by raghu-bhandi** [comment]
issue is with purpose attribute of inputRecord. Internally, SUBSET is used as a default. With that, all fields become optional, and hence default value is not used.

I have analysed the code and the proposed fix is to make purpose as null. No change required any where else.

It is also an opportunity to refactor usage of this attribute. Most places use is if purpose == SUBSET. This can be replaced with a method named allFieldsAreOptional()

**Comment by raghu-bhandi** [comment]
Chetana's fix is the right fix. Issue I raised above is another related issue that came to fore with this. Will add "others" as default for purpose.
