### ISSUE TITLE
Does pushDataToPage handle display of returned json ? What should be ID name and structure

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#9]

**Comment by raghu-bhandi** [comment]
pushDataToPage uses id attribute. It does not use name attribute. from teh json received from server, values are pushed to the tag based on id. for example if josn is {"myName":"James Bond", "state":"CA"....}
and in your html somewhere  <span id="myName"...></span> then the innerHTML of this tag is replaced with James Bond. And, f there is <select id="state"><option value="CA">California</option>......</select>  then california option is selecred.

In general, a tag is matched based on id, and the value is pushed based on the type of tag, including check-box and radio etc..
